runtime: nodejs10
env: standard
service: default
handlers:
  - url: .*
    secure: always
    script: auto
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.9
network:
  session_affinity: true
entrypoint: npm run start:prod
