name: '[CI] On Release Creation'
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create and Copy to ./dist
        run: mkdir dist && cp -r ./!(dist) ./dist/
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to GCloud
        uses: exelban/gcloud@master
        with:
          args: app deploy app.yaml
        env:
          PROJECT_VERSION:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_TOKEN: ${{ secrets.GCLOUD_TOKEN }}
